-
    name: StrikeThrow
    path: StrikeThrow
    score:
        -
            attacker: [WinChance, Damage, DamageDiff, Health]
            defender: [WinChanceDef, DamageDef, DamageDiffDef, HealthDef]
            endstate: HealthZero
            updater: Chipper
            format: DetailedScoreNames
            path: StrikeThrowDetailed.txt
    context:
        set:
            AStartHealth: 5
            BStartHealth: 5
            start: 1
        next:
            attacker: A
            defender: B
            mixup: StrikeThrow
-
    name: ValDeGreyYellow
    path: ValDeGreyYellow
    score:
        -
            attacker: [WinChance, Damage, DamageDiff, Health]
            defender: [WinChanceDef, DamageDef, DamageDiffDef, HealthDef]
            endstate: HealthZero
            updater: Chipper
            format: DetailedScoreNames
            path: ValDeGreyYellowDetailed1.txt
    context:
        set:
            AStartHealth: 5
            BStartHealth: 1
            start: 1
        next:
            attacker: A
            defender: B
            mixup: Yellow vs DeGrey (Magenta Blocked)
-
    name: ValDeGreyYellow
    path: ValDeGreyYellow
    score:
        -
            attacker: [WinChance, Damage, DamageDiff, Health]
            defender: [WinChanceDef, DamageDef, DamageDiffDef, HealthDef]
            endstate: HealthZero
            updater: Chipper
            format: DetailedScoreNames
            path: ValDeGreyYellowDetailed2.txt
    context:
        set:
            AStartHealth: 5
            BStartHealth: 2
            start: 1
        next:
            attacker: A
            defender: B
            mixup: Yellow vs DeGrey (Magenta Blocked)
-
    name: ValDeGreyYellow
    path: ValDeGreyYellow
    score:
        -
            attacker: [WinChance, Damage, DamageDiff, Health]
            defender: [WinChanceDef, DamageDef, DamageDiffDef, HealthDef]
            endstate: HealthZero
            updater: Chipper
            format: DetailedScoreNames
            path: ValDeGreyYellowDetailed3.txt
    context:
        set:
            AStartHealth: 5
            BStartHealth: 3
            start: 1
        next:
            attacker: A
            defender: B
            mixup: Yellow vs DeGrey (Magenta Blocked)
-
    name: ValDeGreyYellow
    path: ValDeGreyYellow
    score:
        -
            attacker: [WinChance, Damage, DamageDiff, Health]
            defender: [WinChanceDef, DamageDef, DamageDiffDef, HealthDef]
            endstate: HealthZero
            updater: Chipper
            format: DetailedScoreNames
            path: ValDeGreyYellowDetailed4.txt
    context:
        set:
            AStartHealth: 5
            BStartHealth: 4
            start: 1
        next:
            attacker: A
            defender: B
            mixup: Yellow vs DeGrey (Magenta Blocked)
-
    name: ValDeGreyYellow
    path: ValDeGreyYellow
    score:
        -
            attacker: [WinChance, Damage, DamageDiff, Health]
            defender: [WinChanceDef, DamageDef, DamageDiffDef, HealthDef]
            endstate: HealthZero
            updater: Chipper
            format: DetailedScoreNames
            path: ValDeGreyYellowDetailed5.txt
    context:
        set:
            AStartHealth: 5
            BStartHealth: 5
            start: 1
        next:
            attacker: A
            defender: B
            mixup: Yellow vs DeGrey (Magenta Blocked)
-
    name: ValDeGreyYellow
    path: ValDeGreyYellow
    score:
        -
            attacker: [WinChance, Damage, DamageDiff, Health]
            defender: [WinChanceDef, DamageDef, DamageDiffDef, HealthDef]
            endstate: HealthZero
            updater: Chipper
            format: DetailedScoreNames
            path: ValDeGreyYellowDetailed6.txt
    context:
        set:
            AStartHealth: 5
            BStartHealth: 6
            start: 1
        next:
            attacker: A
            defender: B
            mixup: Yellow vs DeGrey (Magenta Blocked)
