-
    name: Simple
    path: Simple
    score:
        -
            name: DamageDiff
            endstate: HealthZero
            updater: Chipper
            format: DetailedPartial
            path: SimpleDamage.txt
        -
            name: Win
            endstate: HealthZero
            updater: Chipper
            format: DetailedPartial
            path: SimpleDamage2.txt
    context:
        set:
            AHealth: 4
            BHealth: 4
        next:
            attacker: A
            defender: B
            mixup: MixCorner
