-
    name: StrikeThrow
    path: StrikeThrow
    score:
        -
            attacker: [WinChance, Damage, DamageDiff, Health]
            defender: [WinChanceDef, DamageDef, DamageDiffDef, HealthDef]
            endstate: HealthZero
            updater: Chipper
            format: Detailed
            path: StrikeThrowDetailed.txt
    context:
        set:
            AStartHealth: 6
            BStartHealth: 6
            start: 1
        next:
            attacker: A
            defender: B
            mixup: StrikeThrow
