-
    name: SimpleBig
    path: Simple
    score:
        -
            attacker: Damage
            defender: Damage
            endstate: HealthZero
            updater: Chipper
            format: Detailed
            path: SimpleBigDamage.txt
    context:
        set:
            AHealth: 0
            BHealth: 4
        next:
            attacker: A
            defender: B
            mixup: Mix
-
    name: Simple
    path: Simple
    score:
        -
            attacker: Win
            defender: Win
            endstate: HealthZero
            updater: Chipper
            format: Detailed
            path: SimpleMixWin.txt
        -
            attacker: DamageDiff
            defender: DamageDiff
            endstate: HealthZero
            updater: Chipper
            format: Detailed
            path: SimpleMixDamageDiff.txt
        -
            attacker: Damage
            defender: Damage
            endstate: HealthZero
            updater: Chipper
            format: DetailedPartial
            path: SimpleMixDamage.txt
    context:
        set:
            AHealth: 3
            BHealth: 3
        next:
            attacker: A
            defender: B
            mixup: Mix
-
    name: SimpleCorner
    path: Simple
    score:
        -
            attacker: Win
            defender: Win
            endstate: HealthZero
            updater: Chipper
            format: Detailed
            path: SimpleMixCornerWin.txt
        -
            attacker: DamageDiff
            defender: DamageDiff
            endstate: HealthZero
            updater: Chipper
            format: Detailed
            path: SimpleMixCornerDamageDiff.txt
        -
            attacker: Damage
            defender: Damage
            endstate: HealthZero
            updater: Chipper
            format: Detailed
            path: SimpleMixCornerDamage.txt
    context:
        set:
            AHealth: 3
            BHealth: 3
        next:
            attacker: A
            defender: B
            mixup: MixCorner
-
    name: SimpleFromCorner
    path: Simple
    score:
        -
            attacker: Win
            defender: Win
            endstate: HealthZero
            updater: Chipper
            format: Detailed
            path: SimpleMixFromCornerWin.txt
        -
            attacker: DamageDiff
            defender: DamageDiff
            endstate: HealthZero
            updater: Chipper
            format: Detailed
            path: SimpleMixFromCornerDamageDiff.txt
        -
            attacker: Damage
            defender: Damage
            endstate: HealthZero
            updater: Chipper
            format: Detailed
            path: SimpleMixFromCornerDamage.txt
    context:
        set:
            AHealth: 3
            BHealth: 3
        next:
            attacker: A
            defender: B
            mixup: MixFromCorner
