-
    name: Simple
    path: Simple
    score:
        -
            name: Win
            endstate: HealthZero
            updater: Chipper
            format: Summary
            path: SimpleDamage.txt
        -
            name: Win
            endstate: HealthZero
            updater: Chipper
            format: Detailed
            path: SimpleDamageDiff.txt
        -
            name: Win
            endstate: HealthZero
            updater: Chipper
            format: Detailed
            path: SimpleWin.txt
    context:
        set:
            AHealth: 2
            AChip: 2
            BHealth: 1
            BSuper: 1
        next:
            attacker: A
            defender: B
            mixup: Mix
